nodeLinker: node-modules
enableTelemetry: false
compressionLevel: mixed
defaultSemverRangePrefix: ''
enableGlobalCache: true
enableImmutableInstalls: false
changesetBaseRefs:
  - main
  - origin/main
  - upstream/main
