import { DEEP_LINKS } from '../../constants/page-routes';

export const TOP_BAR_LINKS = [
  DEEP_LINKS.TRANSACTIONS_ALT,
  DEEP_LINKS.ACCOUNTS,
  DEEP_LINKS.CATEGORIES,
  DEEP_LINKS.SUMMARY,
];
export const BOTTOM_BAR_LINKS = [DEEP_LINKS.DASHBOARD, DEEP_LINKS.TRANSACTIONS_ALT, DEEP_LINKS.SUMMARY];
