export const QUERY_KEYS = {
  HI_AUTH_ME: ['hi', 'auth', 'me'],
  HI_USER_PAGINATED: (params: object = {}) => [
    'hi',
    'user',
    'paginated',
    JSON.stringify(params ?? {}),
  ],
  HI_USER_BY_ID: (id: number, params: object = {}) => [
    'hi',
    'user',
    'by-id',
    id,
    JSON.stringify(params ?? {}),
  ],
  HI_APPS_PAGINATED: (params: object = {}) => [
    'hi',
    'apps',
    'paginated',
    JSON.stringify(params ?? {}),
  ],
  HI_APPS_BY_ID: (id: number, params: object = {}) => [
    'hi',
    'apps',
    id,
    JSON.stringify(params ?? {}),
  ],
  HI_APP_PROFILES_PAGINATED: (params: object = {}) => [
    'hi',
    'app-profiles',
    'paginated',
    JSON.stringify(params ?? {}),
  ],
  HI_APP_PROFILES_BY_ID: (id: number, params: object = {}) => [
    'hi',
    'app-profiles',
    'by-id',
    id,
    JSON.stringify(params ?? {}),
  ],
  HI_GROUPS_PAGINATED: (params: object = {}) => [
    'hi',
    'groups',
    'paginated',
    JSON.stringify(params ?? {}),
  ],
  HI_GROUPS_BY_ID: (id: number, params: object = {}) => [
    'hi',
    'groups',
    'by-id',
    id,
    JSON.stringify(params ?? {}),
  ],
  HI_GROUP_MEMBERS_PAGINATED: (params: object = {}) => [
    'hi',
    'group-members',
    'paginated',
    JSON.stringify(params ?? {}),
  ],
  HI_GROUP_MEMBERS_BY_ID: (id: number, params: object = {}) => [
    'hi',
    'group-members',
    'by-id',
    id,
    JSON.stringify(params ?? {}),
  ],
  SPENICLE_ACCOUNT_PAGINATED: (params: object = {}) => [
    'spenicle',
    'account',
    'paginated',
    JSON.stringify(params ?? {}),
  ],
  SPENICLE_ACCOUNT_BY_ID: (id: number, params: object = {}) => [
    'spenicle',
    'account',
    'by-id',
    id,
    JSON.stringify(params ?? {}),
  ],
  SPENICLE_CATEGORY_PAGINATED: (params: object = {}) => [
    'spenicle',
    'category',
    'paginated',
    JSON.stringify(params ?? {}),
  ],
  SPENICLE_CATEGORY_BY_ID: (id: number, params: object = {}) => [
    'spenicle',
    'category',
    'by-id',
    id,
    JSON.stringify(params ?? {}),
  ],
  SPENICLE_TRANSACTION_PAGINATED: (params: object = {}) => [
    'spenicle',
    'transaction',
    'paginated',
    JSON.stringify(params ?? {}),
  ],
  SPENICLE_TRANSACTION_BY_ID: (id: number, params: object = {}) => [
    'spenicle',
    'transaction',
    'by-id',
    id,
    JSON.stringify(params ?? {}),
  ],
  SPENICLE_SUMMARY: (params: object = {}) => [
    'spenicle',
    'summary',
    JSON.stringify(params ?? {}),
  ],
};
