/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/test/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['postTestReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/test/seed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['postTestSeed'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/account/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAccount'];
    put?: never;
    post: operations['postAccount'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/account/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAccountById'];
    put?: never;
    post?: never;
    delete: operations['deleteAccountById'];
    options?: never;
    head?: never;
    patch: operations['patchAccountById'];
    trace?: never;
  };
  '/category/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getCategory'];
    put?: never;
    post: operations['postCategory'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/category/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getCategoryById'];
    put?: never;
    post?: never;
    delete: operations['deleteCategoryById'];
    options?: never;
    head?: never;
    patch: operations['patchCategoryById'];
    trace?: never;
  };
  '/transaction/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getTransaction'];
    put?: never;
    post: operations['postTransaction'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/transaction/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getTransactionById'];
    put?: never;
    post?: never;
    delete: operations['deleteTransactionById'];
    options?: never;
    head?: never;
    patch: operations['patchTransactionById'];
    trace?: never;
  };
  '/summary/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getIndex'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  postTestReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  postTestSeed: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAccount: {
    parameters: {
      query?: {
        id?: number[];
        name?: string[];
        type?: string[];
        search?: string;
        pageNumber?: number;
        pageSize?: number;
        sortBy?: 'created_at' | 'updated_at';
        sortOrder?: 'asc' | 'desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              id: number;
              name: string;
              type: string;
              note: string | null;
              amount: string | number;
              metadata?: unknown;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            pageNumber: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
          };
          'multipart/form-data': {
            items: {
              id: number;
              name: string;
              type: string;
              note: string | null;
              amount: string | number;
              metadata?: unknown;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            pageNumber: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
          };
          'text/plain': {
            items: {
              id: number;
              name: string;
              type: string;
              note: string | null;
              amount: string | number;
              metadata?: unknown;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            pageNumber: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
          };
        };
      };
    };
  };
  postAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
          type: string;
          note: string | null;
          amount: string | number;
          metadata?: unknown;
        };
        'multipart/form-data': {
          name: string;
          type: string;
          note: string | null;
          amount: string | number;
          metadata?: unknown;
        };
        'text/plain': {
          name: string;
          type: string;
          note: string | null;
          amount: string | number;
          metadata?: unknown;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: number;
            name: string;
            type: string;
            note: string | null;
            amount: string | number;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'multipart/form-data': {
            id: number;
            name: string;
            type: string;
            note: string | null;
            amount: string | number;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'text/plain': {
            id: number;
            name: string;
            type: string;
            note: string | null;
            amount: string | number;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
    };
  };
  getAccountById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: number;
            name: string;
            type: string;
            note: string | null;
            amount: string | number;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'multipart/form-data': {
            id: number;
            name: string;
            type: string;
            note: string | null;
            amount: string | number;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'text/plain': {
            id: number;
            name: string;
            type: string;
            note: string | null;
            amount: string | number;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
    };
  };
  deleteAccountById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  patchAccountById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name?: string;
          type?: string;
          note?: string | null;
          amount: string | number;
          metadata?: unknown;
        };
        'multipart/form-data': {
          name?: string;
          type?: string;
          note?: string | null;
          amount: string | number;
          metadata?: unknown;
        };
        'text/plain': {
          name?: string;
          type?: string;
          note?: string | null;
          amount: string | number;
          metadata?: unknown;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: number;
            name: string;
            type: string;
            note: string | null;
            amount: string | number;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'multipart/form-data': {
            id: number;
            name: string;
            type: string;
            note: string | null;
            amount: string | number;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'text/plain': {
            id: number;
            name: string;
            type: string;
            note: string | null;
            amount: string | number;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
    };
  };
  getCategory: {
    parameters: {
      query?: {
        id?: number[];
        name?: string[];
        search?: string;
        pageNumber?: number;
        pageSize?: number;
        sortBy?: 'created_at' | 'updated_at';
        sortOrder?: 'asc' | 'desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              id: number;
              name: string;
              note: string | null;
              metadata?: unknown;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            pageNumber: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
          };
          'multipart/form-data': {
            items: {
              id: number;
              name: string;
              note: string | null;
              metadata?: unknown;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            pageNumber: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
          };
          'text/plain': {
            items: {
              id: number;
              name: string;
              note: string | null;
              metadata?: unknown;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            pageNumber: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
          };
        };
      };
    };
  };
  postCategory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
          note: string | null;
          metadata?: unknown;
        };
        'multipart/form-data': {
          name: string;
          note: string | null;
          metadata?: unknown;
        };
        'text/plain': {
          name: string;
          note: string | null;
          metadata?: unknown;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: number;
            name: string;
            note: string | null;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'multipart/form-data': {
            id: number;
            name: string;
            note: string | null;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'text/plain': {
            id: number;
            name: string;
            note: string | null;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
    };
  };
  getCategoryById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: number;
            name: string;
            note: string | null;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'multipart/form-data': {
            id: number;
            name: string;
            note: string | null;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'text/plain': {
            id: number;
            name: string;
            note: string | null;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
    };
  };
  deleteCategoryById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  patchCategoryById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name?: string;
          note?: string | null;
          metadata?: unknown;
        };
        'multipart/form-data': {
          name?: string;
          note?: string | null;
          metadata?: unknown;
        };
        'text/plain': {
          name?: string;
          note?: string | null;
          metadata?: unknown;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: number;
            name: string;
            note: string | null;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'multipart/form-data': {
            id: number;
            name: string;
            note: string | null;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'text/plain': {
            id: number;
            name: string;
            note: string | null;
            metadata?: unknown;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
    };
  };
  getTransaction: {
    parameters: {
      query?: {
        id?: number[];
        accountId?: number[];
        categoryId?: number[];
        type?: ('income' | 'expense' | 'transfer')[];
        date?: string;
        search?: string;
        pageNumber?: number;
        pageSize?: number;
        sortBy?: 'created_at' | 'updated_at' | 'date';
        sortOrder?: 'asc' | 'desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              id: number;
              accountId: number;
              destinationAccountId: number | null;
              categoryId: number;
              amount: string | number;
              type: 'income' | 'expense' | 'transfer';
              /** Format: date-time */
              date: string;
              note: string | null;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            pageNumber: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
          };
          'multipart/form-data': {
            items: {
              id: number;
              accountId: number;
              destinationAccountId: number | null;
              categoryId: number;
              amount: string | number;
              type: 'income' | 'expense' | 'transfer';
              /** Format: date-time */
              date: string;
              note: string | null;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            pageNumber: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
          };
          'text/plain': {
            items: {
              id: number;
              accountId: number;
              destinationAccountId: number | null;
              categoryId: number;
              amount: string | number;
              type: 'income' | 'expense' | 'transfer';
              /** Format: date-time */
              date: string;
              note: string | null;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            pageNumber: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
          };
        };
      };
    };
  };
  postTransaction: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          accountId: number;
          destinationAccountId: number | null;
          categoryId: number;
          amount: string | number;
          type: 'income' | 'expense' | 'transfer';
          /** Format: date-time */
          date: string;
          note: string | null;
        };
        'multipart/form-data': {
          accountId: number;
          destinationAccountId: number | null;
          categoryId: number;
          amount: string | number;
          type: 'income' | 'expense' | 'transfer';
          /** Format: date-time */
          date: string;
          note: string | null;
        };
        'text/plain': {
          accountId: number;
          destinationAccountId: number | null;
          categoryId: number;
          amount: string | number;
          type: 'income' | 'expense' | 'transfer';
          /** Format: date-time */
          date: string;
          note: string | null;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: number;
            accountId: number;
            destinationAccountId: number | null;
            categoryId: number;
            amount: string | number;
            type: 'income' | 'expense' | 'transfer';
            /** Format: date-time */
            date: string;
            note: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'multipart/form-data': {
            id: number;
            accountId: number;
            destinationAccountId: number | null;
            categoryId: number;
            amount: string | number;
            type: 'income' | 'expense' | 'transfer';
            /** Format: date-time */
            date: string;
            note: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'text/plain': {
            id: number;
            accountId: number;
            destinationAccountId: number | null;
            categoryId: number;
            amount: string | number;
            type: 'income' | 'expense' | 'transfer';
            /** Format: date-time */
            date: string;
            note: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
    };
  };
  getTransactionById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: number;
            accountId: number;
            destinationAccountId: number | null;
            categoryId: number;
            amount: string | number;
            type: 'income' | 'expense' | 'transfer';
            /** Format: date-time */
            date: string;
            note: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'multipart/form-data': {
            id: number;
            accountId: number;
            destinationAccountId: number | null;
            categoryId: number;
            amount: string | number;
            type: 'income' | 'expense' | 'transfer';
            /** Format: date-time */
            date: string;
            note: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'text/plain': {
            id: number;
            accountId: number;
            destinationAccountId: number | null;
            categoryId: number;
            amount: string | number;
            type: 'income' | 'expense' | 'transfer';
            /** Format: date-time */
            date: string;
            note: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
    };
  };
  deleteTransactionById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  patchTransactionById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          accountId?: number;
          destinationAccountId?: number | null;
          categoryId?: number;
          amount?: string | number;
          type?: 'income' | 'expense' | 'transfer';
          /** Format: date-time */
          date?: string;
          note?: string | null;
        };
        'multipart/form-data': {
          accountId?: number;
          destinationAccountId?: number | null;
          categoryId?: number;
          amount?: string | number;
          type?: 'income' | 'expense' | 'transfer';
          /** Format: date-time */
          date?: string;
          note?: string | null;
        };
        'text/plain': {
          accountId?: number;
          destinationAccountId?: number | null;
          categoryId?: number;
          amount?: string | number;
          type?: 'income' | 'expense' | 'transfer';
          /** Format: date-time */
          date?: string;
          note?: string | null;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: number;
            accountId: number;
            destinationAccountId: number | null;
            categoryId: number;
            amount: string | number;
            type: 'income' | 'expense' | 'transfer';
            /** Format: date-time */
            date: string;
            note: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'multipart/form-data': {
            id: number;
            accountId: number;
            destinationAccountId: number | null;
            categoryId: number;
            amount: string | number;
            type: 'income' | 'expense' | 'transfer';
            /** Format: date-time */
            date: string;
            note: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
          'text/plain': {
            id: number;
            accountId: number;
            destinationAccountId: number | null;
            categoryId: number;
            amount: string | number;
            type: 'income' | 'expense' | 'transfer';
            /** Format: date-time */
            date: string;
            note: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
          };
        };
      };
    };
  };
  getSummary: {
    parameters: {
      query: {
        from: string;
        to: string;
        search?: string;
        categoryId?: number[];
        accountId?: number[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: date-time */
            date: string;
            net: number;
            income: number;
            expense: number;
            totalTransactions: number;
          }[];
          'multipart/form-data': {
            /** Format: date-time */
            date: string;
            net: number;
            income: number;
            expense: number;
            totalTransactions: number;
          }[];
          'text/plain': {
            /** Format: date-time */
            date: string;
            net: number;
            income: number;
            expense: number;
            totalTransactions: number;
          }[];
        };
      };
    };
  };
  getIndex: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
